"""Deterministic CSG-IR to dependency-free OpenSCAD compiler."""
from __future__ import annotations
from typing import Any, Mapping
from .ir import Expr, Node, Op, Program, validate


def _num(value: float | int) -> str:
    return f"{float(value):.6g}"


def emit_expr(expr: Expr) -> str:
    if isinstance(expr, (int, float)): return _num(expr)
    if "param" in expr: return str(expr["param"])
    op, args = expr["op"], [emit_expr(x) for x in expr["args"]]
    symbols = {"add": "+", "sub": "-", "mul": "*", "div": "/"}
    if op in symbols: return "(" + f" {symbols[op]} ".join(args) + ")"
    if op in {"min", "max"}: return f"{op}({', '.join(args)})"
    raise ValueError(f"unsupported expression operator: {op}")


def _vector(value: Any) -> str:
    return "[" + ", ".join(emit_expr(x) for x in value) + "]"


def compile_openscad(program: Program, overrides: Mapping[str, float] | None = None) -> str:
    """Compile a validated program, optionally changing public parameter defaults."""
    validate(program, overrides)
    selected = {p.name: p.default for p in program.parameters}
    selected.update(overrides or {})
    nodes = {n.id: n for n in program.nodes}
    lines = ["// Generated by NeuroSCAD; edit parameters, not generated geometry.", "$fn = 64;", ""]
    last_group = None
    for p in program.parameters:
        if p.group != last_group:
            lines.append(f"/* [{p.group}] */")
            last_group = p.group
        if p.label: lines.append(f"// {p.label} ({p.unit})")
        lines.append(f"{p.name} = {_num(selected[p.name])}; // [{_num(p.minimum)}:{_num(p.step)}:{_num(p.maximum)}]")
    lines.extend(["", "/* [Hidden] */", "epsilon = 0.05;", ""])

    def render(node_id: str, depth: int) -> list[str]:
        n: Node = nodes[node_id]
        pad, inner = "  " * depth, "  " * (depth + 1)
        body: list[str]
        if n.op == Op.BOX:
            body = [f"{pad}cube(size={_vector(n.args['size'])}, center=true);"]
        elif n.op == Op.CYLINDER:
            body = [f"{pad}cylinder(d={emit_expr(n.args['d'])}, h={emit_expr(n.args['h'])}, center=true);"]
        elif n.op == Op.SPHERE:
            body = [f"{pad}sphere(d={emit_expr(n.args['d'])});"]
        else:
            keyword = {Op.UNION: "union", Op.DIFFERENCE: "difference", Op.INTERSECTION: "intersection"}[n.op]
            body = [f"{pad}{keyword}() {{"]
            for child in n.children: body.extend(render(child, depth + 1))
            body.append(f"{pad}}}")
        has_rotate = any(x != 0 for x in n.rotate)
        has_translate = any(x != 0 for x in n.translate)
        for keyword, vector, enabled in (("rotate", n.rotate, has_rotate), ("translate", n.translate, has_translate)):
            if enabled:
                body = [f"{pad}{keyword}({_vector(vector)}) {{"] + ["  " + x for x in body] + [f"{pad}}}"]
        return body
    lines.extend(render(program.root, 0))
    return "\n".join(lines) + "\n"
