// Generated by NeuroSCAD; edit parameters, not generated geometry.
$fn = 64;

/* [Dimensions] */
// Диаметр трубы (mm)
tube_d = 25; // [8:0.5:80]
// Толщина стенки (mm)
wall = 4; // [2:0.5:12]
// Ширина хомута (mm)
clamp_width = 20; // [8:1:50]
// Зазор разреза (mm)
split_gap = 3; // [1:0.5:10]
// Отверстие под винт (mm)
screw_d = 4.4; // [2:0.1:12]
// Длина проушины (mm)
lug_length = 18; // [10:1:40]
// Высота проушины (mm)
lug_height = 14; // [14:1:30]

/* [Hidden] */
epsilon = 0.05;

difference() {
  union() {
    cylinder(d=(tube_d + (2 * wall)), h=clamp_width, center=true);
    translate([(((tube_d + (2 * wall)) / 2) + (lug_length / 2) + -1), 0, 0]) {
      cube(size=[lug_length, lug_height, clamp_width], center=true);
    }
  }
  cylinder(d=tube_d, h=(clamp_width + 2), center=true);
  translate([(((tube_d + (2 * wall)) / 2) + (lug_length / 2)), 0, 0]) {
    cube(size=[(wall + lug_length + 2), split_gap, (clamp_width + 2)], center=true);
  }
  translate([(((tube_d + (2 * wall)) / 2) + (lug_length / 2)), 0, 0]) {
    rotate([90, 0, 0]) {
      cylinder(d=screw_d, h=(lug_height + 2), center=true);
    }
  }
}
